windowrule = float 1, match:class nm-connection-editor
windowrule = float 1, match:title ^(Open|Save)
windowrule = pin 1, match:title Picture-in-Picture
windowrule = suppress_event maximize, match:class .*
