#!/usr/bin/env bash
set -euo pipefail

# MinerU "Perfect" Cleanup Script (v2.0.1)
# ────────────────────────────────────────────────────────────────────────────
# PURPOSE:
#   MinerU produces a lot of "junk" artifacts (visual debugging PDFs,
#   intermediate layout JSONs, etc.) that aren't needed for LLM ingestion.
#   This script recursively cleans those up while preserving the core Markdown.

VERSION="2.0.1"

# ── Color Definitions for User Feedback ──────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# ── Help Message Documentation ───────────────────────────────────────────────
show_help() {
    cat << EOF
Usage: $(basename "$0") [OPTIONS] [TARGET_DIR]

A perfect cleanup utility for MinerU output artifacts. 

Options:
  -d, --dry-run    Show what would be removed without actually deleting.
  -f, --force      Force removal without confirmation.
  -r, --recursive  Recursively clean subdirectories.
  -h, --help       Show this help message and exit.
  -v, --version    Show version information.

If TARGET_DIR is not specified, the current directory is used.

Files removed:
  * _layout.pdf, _span.pdf, _origin.pdf (Visual debugging)
  * _content_list.json, _middle.json, _model.json (Intermediate data)
  * model_output.txt (Log artifacts)
  * Empty directories resulting from cleanup.
EOF
}

# ── Default Settings ─────────────────────────────────────────────────────────
TARGET_DIR=""
DRY_RUN=false
FORCE=false
RECURSIVE=false

# ── Argument Parsing Logic ───────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            show_help
            exit 0
            ;;
        -v|--version)
            echo "clean-mineru version $VERSION"
            exit 0
            ;;
        -d|--dry-run)
            DRY_RUN=true
            shift
            ;;
        -f|--force)
            FORCE=true
            shift
            ;;
        -r|--recursive)
            RECURSIVE=true
            shift
            ;;
        --completion)
            # ── Shell Completion Generation ──────────────────────────────────
            # This block outputs a Zsh completion script that Nix can use to
            # provide tab-completion for flags and directories.
            cat << 'EOF'
_clean_mineru_completion() {
    local -a opts
    opts=(
        "-d" "--dry-run"
        "-f" "--force"
        "-r" "--recursive"
        "-h" "--help"
        "-v" "--version"
    )
    if [[ $PREFIX == -* ]]; then
        _describe 'options' opts
    else
        _files -/
    fi
}
compdef _clean_mineru_completion clean-mineru
EOF
            exit 0
            ;;
        -*)
            echo -e "${RED}Error: Unknown option $1${NC}"
            show_help
            exit 1
            ;;
        *)
            TARGET_DIR="$1"
            shift
            ;;
    esac
done

# ── Smart Directory Selection (fzf Integration) ──────────────────────────────
# If no directory is provided as an argument, we try to use fzf for an
# interactive selection experience.
if [ -z "$TARGET_DIR" ]; then
    if command -v fzf >/dev/null 2>&1; then
        echo -e "${BLUE}No directory specified. Launching fzf for selection...${NC}"
        # We search up to 3 levels deep for directories to choose from
        TARGET_DIR=$(find . -maxdepth 3 -type d 2>/dev/null | fzf --prompt="Select MinerU output directory: " --height=40% --reverse)
        if [ -z "$TARGET_DIR" ]; then
            echo -e "${YELLOW}Selection cancelled.${NC}"
            exit 0
        fi
    else
        # Fallback to current directory if fzf is missing
        TARGET_DIR="."
    fi
fi

# ── Validation ───────────────────────────────────────────────────────────────
if [ ! -d "$TARGET_DIR" ]; then
    echo -e "${RED}Error: Directory '$TARGET_DIR' does not exist.${NC}"
    exit 1
fi

# Expand to absolute path for consistent logging
TARGET_DIR=$(realpath "$TARGET_DIR")

echo -e "${BLUE}Cleaning MinerU artifacts in: ${YELLOW}$TARGET_DIR${NC}"
if [ "$DRY_RUN" = true ]; then
    echo -e "${YELLOW}*** DRY RUN MODE - No files will be deleted ***${NC}"
fi

# ── Cleanup Patterns ─────────────────────────────────────────────────────────
# These are the specific file patterns generated by MinerU that we want to purge.
PATTERNS=(
    "*_layout.pdf"        # Visual layout detection results
    "*_span.pdf"          # Span detection debugging
    "*_origin.pdf"        # Copy of the original input
    "*_content_list.json" # Intermediate structured lists
    "*_middle.json"       # Hidden intermediate processing state
    "*_model.json"        # Raw model inference results
    "model_output.txt"    # Log file artifact
)

# ── Find Command Construction ───────────────────────────────────────────────
# We build a 'find' command dynamically based on the --recursive flag.
FIND_CMD=("find" "$TARGET_DIR")
if [ "$RECURSIVE" = false ]; then
    FIND_CMD+=("-maxdepth" "1")
fi

# Build the OR logic for 'find' patterns (e.g. -name p1 -o -name p2)
PATTERN_ARGS=()
for i in "${!PATTERNS[@]}"; do
    if [ $i -gt 0 ]; then
        PATTERN_ARGS+=("-o")
    fi
    PATTERN_ARGS+=("-name" "${PATTERNS[$i]}")
done

# ── File Deletion Loop ───────────────────────────────────────────────────────
total_removed=0

# We dump the matches into a temporary file to safely handle spaces in paths
temp_list=$(mktemp)
"${FIND_CMD[@]}" \( "${PATTERN_ARGS[@]}" \) -type f > "$temp_list"

while IFS= read -r file; do
    if [ "$DRY_RUN" = true ]; then
        echo -e "${BLUE}[DRY-RUN] Will remove: ${NC}$file"
    else
        if [ "$FORCE" = true ]; then
            rm -f "$file"
            echo -e "${RED}[REMOVED]${NC} $file"
        else
            # Interactive confirmation unless --force is used
            echo -n "Remove $file? [y/N] "
            read -r response
            if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
                rm -f "$file"
                echo -e "${RED}[REMOVED]${NC} $file"
            else
                echo "Skipping $file"
                continue
            fi
        fi
    fi
    ((total_removed += 1))
done < "$temp_list"
rm "$temp_list"

# ── Empty Directory Cleanup ──────────────────────────────────────────────────
# MinerU often creates subfolders that become completely empty after we
# remove the intermediate PDFs/JSONs. We purge those to keep the tree clean.
echo -e "${BLUE}Cleaning up empty directories...${NC}"
if [ "$DRY_RUN" = true ]; then
    find "$TARGET_DIR" -type d -empty -not -path "$TARGET_DIR" -exec echo -e "${BLUE}[DRY-RUN] Will remove empty dir: ${NC}{}" \;
else
    # We do this recursively by default for empty leaf nodes
    find "$TARGET_DIR" -type d -empty -not -path "$TARGET_DIR" -delete
fi

# ── Final Status Report ──────────────────────────────────────────────────────
echo
if [ "$DRY_RUN" = true ]; then
    echo -e "${GREEN}Dry run finished. $total_removed files would be removed.${NC}"
else
    echo -e "${GREEN}Cleanup finished. $total_removed files removed.${NC}"
fi
