import os
import shutil
import re

source_dir = "/home/qwerty/Music/new"
target_base = "/home/qwerty/Music"

# Comprehensive mappings - Order matters (more specific first)
mappings = [
    ("renee", "renee-sales"),
    ("PARDON", "A_KIM_OK_PARDON"),
    ("Glichery", "Glichery - Sea Of Problems"),
    ("Sea of Problems", "Glichery - Sea Of Problems"),
    ("Cult Member", "And_I_can_t_wait_anymore_X_u_weren_t_here_I_really_miss_you"),
    ("weren't here", "And_I_can_t_wait_anymore_X_u_weren_t_here_I_really_miss_you"),
    ("werent here", "And_I_can_t_wait_anymore_X_u_weren_t_here_I_really_miss_you"),
    ("Starly", "starly"),
    ("Flashbacks", "flashbacks"),
    ("eclipser", "eclipser"),
    ("Eyedress", "Eyedress"),
    ("Molchat Doma", "Kletka"),
    ("клетка", "Kletka"),
    ("судно", "sudno"),
    ("тоска", "toska"),
    ("tom tom", "holy fuck - tom tom"),
    ("Estilo Horizonte", "estilo horizonte de diamante"),
    ("HORIZONTE DIAMANTE", "estilo horizonte de diamante"),
    ("NOOT NOOT", "NOOT NOOT"),
    ("give me everything", "givemeeverything-yochico"),
    ("yo chico", "givemeeverything-yochico"),
    ("B2B", "b2b"),
    ("Crystals", "Crystals"),
    ("Munchausen", "munchausen"),
    ("Satisfaction", "looksmaxx"),
    ("ICEWHORE", "looksmaxx"),
    ("ICE WHORE", "looksmaxx"),
    ("Keraunos", "keraunos"),
    ("Angel Echo", "Angel Echo"),
    ("Why Not", "Why Not"),
    ("KAMAMESHI", "KAMAMESHI"),
    ("INCOMING", "INCOMING"),
    ("TWILIGHT", "TWILIGHT"),
    ("6.5", "6.5"),
    ("Override", "Override"),
    ("Scary Garry", "Scary Garry"),
    ("suffer with me", "suffer with me"),
    ("one chance", "aggressive phonk"),
    ("VØJ", "narvent"),
    ("Narvent", "narvent"),
    ("Mareux", "loversfromthepast"),
    ("Lovers From The Past", "loversfromthepast"),
    ("silhouette", "pastel_ghost"),
    ("Taking Drugs", "takingdrugs"),
    ("mall grab", "mall_grab"),
    ("Mall Grab", "mall_grab"),
    ("Rammstein", "rammstein"),
    ("Cool for the Summer", "coolforthesummer"),
    ("wush_2", "wush_2"),
    ("Smezir_2", "smezir"),
    ("DO OR DIE", "DO OR DIE"),
    ("Welcome And Goodbye", "Welcome And Goodbye"),
    ("Internet Shelter", "akiaura"),
    ("Vois Sur Ton Chemin", "exorcist"),
    ("GREEN ORXNGE", "GREEN ORXNGE"),
    ("Les", "les"),
    ("particles", "villiam_lane"),
    ("SUNRISE", "aura"),
    ("Shadow", "shadow"),
    ("LO0K", "LO0k"),
    ("BEVLYNOUS", "bevynous"),
    ("PHONKY TOWN", "aggressive phonk"),
    ("PRINCE OF DARKNESS", "aggressive phonk"),
    ("GigaChad", "status"),
    ("Monolithic", "status"),
    ("Subtronics", "subtronics"),
    ("SUICIDAL-IDOL", "suicidal-idol"),
    ("Tak Tak Funk", "taktak"),
    ("Tame Impala", "tim_impala"),
    ("The lost soul down", "thelostsoul"),
    ("The Matrix", "hacker"),
    ("The Perfect Girl", "perfect_girl"),
    ("TRXVELER", "Trxveler"),
    ("Twin Tribes", "Twin Tribes"),
    ("Vem Vem", "Vem Vem"),
    ("VISION", "vision"),
    ("vowl", "vowl"),
    ("wutiwant", "wutiwant"),
    ("XAN$X", "XAN$X"),
    ("Yeat", "yeat"),
    ("Marwan Moussa", "MarwanMoussa"),
    ("مروان موسى", "MarwanMoussa"),
    ("Marwan", "MarwanMoussa"),
    ("مروان", "MarwanMoussa"),
    ("ride or die", "rideordie"),
    ("Pathetic", "dancingnihilist"),
    ("Isolated Dream", "akiaura"),
    ("veil", "akiaura"),
    ("al1en_jump", "al1en_jump"),
    ("Cold Lie", "coldlie"),
    ("Drowning", "akiaura"),
    ("2000", "akiaura"),
    ("Scythermane", "coldlie"),
    ("LXNGVX", "coldlie"),
    ("Dyzphoria", "Can't_relate_Dyzphoria"),
    ("Miguel Angeles", "protectioncharm"),
    ("Protection Charm", "protectioncharm"),
    ("MaRo", "dancingnihilist"),
    ("Dancing Nihilist", "dancingnihilist"),
    ("Orange Sector", "farben"),
    ("No_4mat", "no_4mat"),
    ("No 4mat", "no_4mat"),
    ("Baltra", "Never_Let_Go_Of_Me_baltra"),
    ("never let go", "Never_Let_Go_Of_Me_baltra"),
    ("Stressed Out", "Tomsize x Twenty One Pilots - Stressed Out"),
    ("Napalm Death", "Napalm Death"),
    ("You suffer", "Napalm Death"),
    ("Night Drive", "nightdrive"),
    ("Wilee", "nightdrive"),
    ("Young Black and Rich", "Young Black and Rich"),
    ("Melly Mike", "Young Black and Rich"),
    ("TOXIC", "YOUNGX777"),
    ("YOUNGX777", "YOUNGX777"),
    ("You're gone", "You're gone"),
    ("YOUR NAME", "YOUR NAME"),
    ("Zeds Dead", "subtronics"),
    ("Gassed Up", "subtronics"),
    ("Отменяй", "Отменяй"),
    ("Marwan Moussa", "MarwanMoussa"),
    ("MASAFAT", "MarwanMoussa"),
    ("Clubbed to Death", "hacker"),
    ("Matrix", "hacker"),
    ("Temperature", "Temperature"),
    ("TEENWXVE", "Anatomy"),
    ("Anatomy", "Anatomy"),
    ("Synthetic", "Synthetic"),
    ("ecstacy", "suicidal-idol"),
    ("After Dark", "After Dark"),
    ("Tom Platz", "After Dark"),
    ("BAIXO", "baixo"),
    ("Dark Side", "XAN$X"),
    ("NXSTY BLOOD", "aggressive phonk"),
    ("Wels", "aggressive phonk"),
    ("Baby dont hurt me", "What is love"),
    ("What is love", "What is love"),
    ("Who Gives A Fuck", "deathrattle"),
    ("David Goggins", "deathrattle"),
    ("Monolith", "Twin Tribes"),
    ("envy", "envy"),
    ("Oppenheimer", "hacker"),
    ("INSIDE ME", "insideMe"),
    ("Tonight", "insomnia"),
    ("RITMO DE VERAO", "baixo"),
    ("Borderline", "tim_impala"),
    ("Same Old Mistakes", "tim_impala"),
    ("AKAI", "aggressive phonk"),
    ("alone again", "aloneagain"),
    ("Apogee", "akiaura"),
    ("NIVEK FFORHS", "aggressive phonk"),
    ("Missing Textures", "aggressive phonk"),
    ("Rumors", "chill"),
    ("Bright Lights", "chill"),
    ("pastel ghost", "pastel_ghost"),
    ("iris", "pastel_ghost"),
    ("lilacs", "pastel_ghost"),
    ("Kerosene", "aggressive phonk"),
    ("Mercury", "aggressive phonk"),
    ("DEATH TRIAL", "death_trial"),
    ("DRESS!", "akiaura"),
    ("Soldier", "chill"),
    ("Destiny", "chill"),
    ("SPACE!", "aura"),
    ("FORGOTTEN CHILD", "forgotten_child"),
    ("Runaway", "chill"),
    ("Resonance", "chill"),
    ("playboi carti", "immortal"),
    ("Artemas", "chill"),
    ("Lets Go Gambling", "status"),
    ("X-Slide", "status"),
    ("Devil eyes", "devileyes"),
    ("BLIZZARD", "aura"),
    ("my honest reaction", "luxury_honestreaction"),
    ("Want To Love", "wanttolove"),
    ("CALA BONITA", "baixo"),
    ("FALL FROM THE SKY", "fly_home_buddy_I_wear_cologne_fallfromthesky"),
    ("little dark age", "littledarkage"),
    ("immortal", "immortal"),
    ("Don't Stop", "chill"),
    ("pride", "aggressive phonk"),
    ("Bohemian", "chill"),
    ("numb", "chill"),
    ("help_urself", "helpurself"),
    ("Echoes", "aura"),
    ("ESPAÇO LIMINAL", "aura"),
    ("New Horizons", "chill"),
    ("SimpsonWave1995", "chill"),
    ("Возвращайся", "vielleicht"),
    ("Возвращайся", "vielleicht"),
    ("LIKE ME", "looksmaxx"),
    ("Linkin Park", "chill"),
    ("In The End", "chill"),
    ("lost", "chill"),
    ("luvGhost", "akiaura"),
    ("M4GN", "baixo"),
    ("BIG MOOD", "MarwanMoussa"),
    ("CHAMPIONS LEAGUE", "MarwanMoussa"),
    ("MENTE MÁ", "baixo"),
    ("MERCY", "aggressive phonk"),
    ("Metamorphosis", "metamophosis"),
    ("MIDNIGHT", "aggressive phonk"),
    ("Million Dollar Baby", "looksmaxx"),
    ("Mist", "akiaura"),
    ("mountains", "hacker"),
    ("No time for Caution", "hacker"),
    ("S.T.A.Y", "hacker"),
    ("Hans Zimmer", "hacker"),
    ("I Hate Society", "hacker"),
    ("Main Theme", "hacker"),
    ("MTG GOSTA", "baixo"),
    ("MURDER IN MY MIND", "aggressive phonk"),
    ("NEXT UP", "baixo"),
    ("NIGHTCLUB", "akiaura"),
    ("nightmare", "aloneagain"),
    ("Notion", "the days"),
    ("Suffocation", "akiaura"),
    ("OLHA A MENSAGEM", "baixo"),
    ("snowfall", "chill"),
    ("Our Country Has Fallen", "status"),
    ("Prayer", "chill"),
    ("PT FOSTERS", "aggressive phonk"),
    ("PUCH udiennx", "acido"),
    ("PULSE", "pulsebreaker"),
    ("freak show", "chill"),
    ("freakshow", "chill"),
    ("Rap God", "chill"),
    ("RAPTURE", "aggressive phonk"),
    ("Rei", "akiaura"),
    ("Righteous", "chill"),
    ("Rio", "MarwanMoussa"),
    ("Dj Lucaxs", "baixo"),
    ("Rockstar Made", "immortal"),
    ("Running In The Dark", "chill"),
    ("Rust Cohle", "chill"),
    ("Unfair", "chill"),
    ("Sahara", "aggressive phonk"),
    ("DEMONS IN MY SOUL", "aggressive phonk"),
    ("SEQUÊNCIA DO MADRUGADA", "baixo"),
    ("Shook Ones", "chill"),
    ("Show Me Your Back", "aggressive phonk"),
    ("sidewalks and skeletons", "crystalcastles"),
    ("goth", "crystalcastles"),
    ("simpsonwave", "chill"),
    ("Snow Strippers", "crystalcastles"),
    ("Under Your Spell", "underyourspell"),
    ("softcore", "chill"),
    ("tell em", "chill"),
    ("Stereo Love", "chill"),
    ("waisetsu", "akiaura"),
    ("Waiting", "chill"),
    ("LEGACY", "aggressive phonk"),
    ("DYSTOPIA", "aggressive phonk"),
    ("Flare", "aggressive phonk"),
    ("SLAY", "akiaura"),
    ("BLAH", "akiaura"),
    ("clima lindo", "baixo"),
    ("Untitled 05", "chill"),
    ("Grateful", "chill"),
    ("L'Amour Toujours", "chill"),
    ("EEYUH!","baixo"),
    ("Fight Back", "chill"),
    ("Hier Encore", "chill"),
    ("EMPIRE", "aggressive phonk"),
    ("Dark Triad", "status"),
    ("I Came To Rome", "status"),
    ("Dark Chrysolite", "aggressive phonk"),
    ("DEAD END", "aggressive phonk"),
    ("gonna cry", "status"),
    ("GLORY", "aggressive phonk"),
    ("black suit theme", "hacker"),
    ("Ashes", "chill"),
    ("got drip", "status"),
    ("DEATH RATTLE", "deathrattle"),
    ("BURACO", "baixo"),
    ("FLUX X WAVE", "akiaura"),
    ("Solitude", "chill"),
    ("Redchinawave", "akiaura"),
    ("Petrichor", "aggressive phonk"),
    ("stellar", "chill"),
    ("hide the pain", "status"),
    ("PSL", "status"),
    ("NITE", "akiaura"),
    ("Come Back", "vielleicht"),
    ("Failure", "status"),
    ("Somewhere We Can Go", "chill"),
    ("Human Malice", "aggressive phonk"),
    ("MELODIA DA ALAMEDA", "baixo"),
    ("Never Give Up", "chill"),
    ("Redemption", "aggressive phonk"),
    ("places bfdi", "akiaura"),
    ("Secrets", "chill"),
    ("Bully Maguire", "status"),
    ("Pussy Podium", "akiaura"),
    ("spookiest beat", "status"),
    ("econ yalu", "baixo"),
    ("Don't Stop", "chill"),
    ("FORCE!", "aggressive phonk"),
    ("DRESS", "akiaura"),
    ("ENOUGH!", "akiaura"),
    ("JUMP STYLE", "jumpstyle"),
    ("InEssence", "status"),
    ("GTA IV", "hacker"),
    ("Mountains", "hacker"),
    ("poster boy", "akiaura"),
    ("Under Your Spell", "underyourspell"),
    ("truest form is evil", "aggressive phonk"),
    ("OLHA MENSAGEM", "baixo"),
    ("CDG", "MarwanMoussa"),
    ("On The Run", "hacker"),
    ("Pussy Podium", "akiaura"),
    ("immortal", "immortal"),
    ("Go!", "chill"),
    ("alone again", "aloneagain"),
    ("dionysus", "dionnysuss"),
    ("fangs", "dionnysuss"),
    ("Farben", "farben"),
    ("Free Bird", "chill"),
    ("Home", "chill"),
    ("Far Away", "chill"),
    ("Dimensions", "chill"),
    ("Gallowdance", "Kletka"),
    ("Bent FORTE!", "akiaura"),
    ("Mac Quayle", "hacker"),
    ("DARE", "chill"),
    ("Childhood Memories", "chill"),
    ("Hive", "aggressive phonk"),
    ("Back To You", "chill"),
    ("Cold", "chill"),
    ("Twisty", "jumpstyle"),
    ("DRESS!", "akiaura"),
]

# Get all directories in target_base to try and match automatically
target_dirs = [d for d in os.listdir(target_base) if os.path.isdir(os.path.join(target_base, d))]

for f in os.listdir(source_dir):
    source_path = os.path.join(source_dir, f)
    if not os.path.isfile(source_path):
        continue
        
    lowered = f.lower()
    moved = False
    
    # Try manual mappings first
    for keyword, target_sub in mappings:
        if keyword.lower() in lowered:
            target_dir = os.path.join(target_base, target_sub)
            os.makedirs(target_dir, exist_ok=True)
            print(f"Moving: {f} -> {target_sub}")
            shutil.move(source_path, os.path.join(target_dir, f))
            moved = True
            break
            
    if not moved:
        # Try automatic directory matching
        for d in target_dirs:
            # Skip very short directory names and generic ones
            if len(d) > 3 and d.lower() in lowered:
                target_dir = os.path.join(target_base, d)
                print(f"Auto-moving: {f} -> {d}")
                shutil.move(source_path, os.path.join(target_dir, f))
                moved = True
                break
    
    if not moved:
        # Move to MISC if still unsorted
        target_dir = os.path.join(target_base, "MISC")
        os.makedirs(target_dir, exist_ok=True)
        print(f"Moving to MISC: {f}")
        shutil.move(source_path, os.path.join(target_dir, f))
